### ISSUE TITLE
iOS app

### ISSUE THREAD

**Issue by orthecreedence** [turtl/tracker#24]
Might split the `mobile` project into `android` and `ios` for this because it already has some android-specific stuff in there, and I feel like it's just going to become a spaghetti mess to try to have one codebase for both targets.

I finally have a Mac that runs XCode, so this should be a go after v0.7.0 launches.

---

## TODO (required)

- [x] Open external links in external browser
- [x] Fix `Login Failed -- TypeError: null is not an object` on login
- [x] Hide dumb cordova loading screen
- [x] Set Turtl icon
- [ ] File downloads / uploads
- [ ] Integrate camera

## TODO (may come later / separate issues)

- [x] Integrate keychain for staying logged in
- [ ] Integrate "share to Turtl"

**Comment by orthecreedence** [comment]
![turtl_ios](https://user-images.githubusercontent.com/220134/50577093-ae4cb000-0dd4-11e9-96cd-bdf6ccd0a781.png)

Looking good! Got it running in a simulator =]

Would love if someone could review the interface between the app and the core (since this is my first time writing ObjC): https://github.com/turtl/ios/blob/master/bundle/cordova-plugin-turtl-core/src/ios/TurtlCore.m

Happy new year, everyone!

**Comment by colbach** [comment]
Is the iOS-App still in work? Does there is any estimation, when we can expect Turtl for iOS?
I would not have any problem to pay for this app. This would be a good Opportunity to finance the project. I guess this will reach an bigger number of paying users, than your Premium subscription.

**Comment by njakes** [comment]
I am very interested in using this but am hesitant to go all in without an iOS app.  Do you have any projected timeline?  Do you have any development builds that you need help testing?

**Comment by colbach** [comment]
I saw that there were no commits since January on the iOS code repository. Is this project still active?

**Comment by fivestones** [comment]
Still hoping for an iOS app! :-)

**Comment by dontcrash** [comment]
I’m guessing this isn’t a priority :(

**Comment by orthecreedence** [comment]
It is. There's just a lot of stuff I'm juggling right now. I'm slowly picking away at #52 (WASM) which requires a fairly in-depth rearchitect of the core, and would also make deployment to environments like iOS much easier.

**Comment by orthecreedence** [comment]
Oops, submitted too early and hit the wrong button.

Was going to say that my nights and weekends time is pretty limited and might be for a while, so this is all moving at a snail's pace. Ultimately, unless I get hit by a bus (or more likely a redwood in my case) this will get done eventually!

**Comment by lisapparition** [comment]
So nice to see the iOS app is still in development! I know it's completely different from android and you're doing a bunch of stuff right now, but I really hope it comes out someday. I love Turtl and being able to use it on my phone or perhaps iPad would be a dream come true for me.

**Comment by Xiyitifu** [comment]
Hi, any news about it ? 😊

**Comment by bitstr3am** [comment]
No hard feelings as software takes time but iOS was projected in 2019, now 2024. It's clearly not resourced. I hope it happens one day but for foreseeable future Turtl is blocked for iOS users. Please do update us if that really changes.

**Comment by sus390** [comment]
need ios version

**Comment by notiuneoffiicial** [comment]
I would really like to work on this - would love a conversation with whoever has last worked to understand what the intended goal was in making the ios app different than android - at the very least would like to get the core app built for ios
